// Code generated by "go-enum -type=OperationResult"; DO NOT EDIT.

// Install go-enum by `go get install github.com/searKing/golang/tools/go-enum`
package controller

import (
	"database/sql"
	"database/sql/driver"
	"encoding"
	"encoding/json"
	"fmt"
	"strconv"
)

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ResourceUnchanged-0]
	_ = x[ResourceCreated-1]
	_ = x[ResourceUpdated-2]
}

const _OperationResult_name = "ResourceUnchangedResourceCreatedResourceUpdated"

var _OperationResult_index = [...]uint8{0, 17, 32, 47}

func _() {
	var _nil_OperationResult_value = func() (val OperationResult) { return }()

	// An "cannot convert OperationResult literal (type OperationResult) to type fmt.Stringer" compiler error signifies that the base type have changed.
	// Re-run the go-enum command to generate them again.
	var _ fmt.Stringer = _nil_OperationResult_value
}

func (i OperationResult) String() string {
	if i < 0 || i >= OperationResult(len(_OperationResult_index)-1) {
		return "OperationResult(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _OperationResult_name[_OperationResult_index[i]:_OperationResult_index[i+1]]
}

// New returns a pointer to a new addr filled with the OperationResult value passed in.
func (i OperationResult) New() *OperationResult {
	clone := i
	return &clone
}

var _OperationResult_values = []OperationResult{0, 1, 2}

var _OperationResult_name_to_values = map[string]OperationResult{
	_OperationResult_name[0:17]:  0,
	_OperationResult_name[17:32]: 1,
	_OperationResult_name[32:47]: 2,
}

// ParseOperationResultString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func ParseOperationResultString(s string) (OperationResult, error) {
	if val, ok := _OperationResult_name_to_values[s]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to OperationResult values", s)
}

// OperationResultValues returns all values of the enum
func OperationResultValues() []OperationResult {
	return _OperationResult_values
}

// IsAOperationResult returns "true" if the value is listed in the enum definition. "false" otherwise
func (i OperationResult) Registered() bool {
	for _, v := range _OperationResult_values {
		if i == v {
			return true
		}
	}
	return false
}

func _() {
	var _nil_OperationResult_value = func() (val OperationResult) { return }()

	// An "cannot convert OperationResult literal (type OperationResult) to type encoding.BinaryMarshaler" compiler error signifies that the base type have changed.
	// Re-run the go-enum command to generate them again.
	var _ encoding.BinaryMarshaler = &_nil_OperationResult_value

	// An "cannot convert OperationResult literal (type OperationResult) to type encoding.BinaryUnmarshaler" compiler error signifies that the base type have changed.
	// Re-run the go-enum command to generate them again.
	var _ encoding.BinaryUnmarshaler = &_nil_OperationResult_value
}

// MarshalBinary implements the encoding.BinaryMarshaler interface for OperationResult
func (i OperationResult) MarshalBinary() (data []byte, err error) {
	return []byte(i.String()), nil
}

// UnmarshalBinary implements the encoding.BinaryUnmarshaler interface for OperationResult
func (i *OperationResult) UnmarshalBinary(data []byte) error {
	var err error
	*i, err = ParseOperationResultString(string(data))
	return err
}

func _() {
	var _nil_OperationResult_value = func() (val OperationResult) { return }()

	// An "cannot convert OperationResult literal (type OperationResult) to type json.Marshaler" compiler error signifies that the base type have changed.
	// Re-run the go-enum command to generate them again.
	var _ json.Marshaler = _nil_OperationResult_value

	// An "cannot convert OperationResult literal (type OperationResult) to type encoding.Unmarshaler" compiler error signifies that the base type have changed.
	// Re-run the go-enum command to generate them again.
	var _ json.Unmarshaler = &_nil_OperationResult_value
}

// MarshalJSON implements the json.Marshaler interface for OperationResult
func (i OperationResult) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for OperationResult
func (i *OperationResult) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("OperationResult should be a string, got %s", data)
	}

	var err error
	*i, err = ParseOperationResultString(s)
	return err
}

func _() {
	var _nil_OperationResult_value = func() (val OperationResult) { return }()

	// An "cannot convert OperationResult literal (type OperationResult) to type encoding.TextMarshaler" compiler error signifies that the base type have changed.
	// Re-run the go-enum command to generate them again.
	var _ encoding.TextMarshaler = _nil_OperationResult_value

	// An "cannot convert OperationResult literal (type OperationResult) to type encoding.TextUnmarshaler" compiler error signifies that the base type have changed.
	// Re-run the go-enum command to generate them again.
	var _ encoding.TextUnmarshaler = &_nil_OperationResult_value
}

// MarshalText implements the encoding.TextMarshaler interface for OperationResult
func (i OperationResult) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for OperationResult
func (i *OperationResult) UnmarshalText(text []byte) error {
	var err error
	*i, err = ParseOperationResultString(string(text))
	return err
}

//func _() {
//	var _nil_OperationResult_value = func() (val OperationResult) { return }()
//
//	// An "cannot convert OperationResult literal (type OperationResult) to type yaml.Marshaler" compiler error signifies that the base type have changed.
//	// Re-run the go-enum command to generate them again.
//	var _ yaml.Marshaler = _nil_OperationResult_value
//
//	// An "cannot convert OperationResult literal (type OperationResult) to type yaml.Unmarshaler" compiler error signifies that the base type have changed.
//	// Re-run the go-enum command to generate them again.
//	var _ yaml.Unmarshaler = &_nil_OperationResult_value
//}

// MarshalYAML implements a YAML Marshaler for OperationResult
func (i OperationResult) MarshalYAML() (interface{}, error) {
	return i.String(), nil
}

// UnmarshalYAML implements a YAML Unmarshaler for OperationResult
func (i *OperationResult) UnmarshalYAML(unmarshal func(interface{}) error) error {
	var s string
	if err := unmarshal(&s); err != nil {
		return err
	}

	var err error
	*i, err = ParseOperationResultString(s)
	return err
}

func _() {
	var _nil_OperationResult_value = func() (val OperationResult) { return }()

	// An "cannot convert OperationResult literal (type OperationResult) to type driver.Valuer" compiler error signifies that the base type have changed.
	// Re-run the go-enum command to generate them again.
	var _ driver.Valuer = _nil_OperationResult_value

	// An "cannot convert OperationResult literal (type OperationResult) to type sql.Scanner" compiler error signifies that the base type have changed.
	// Re-run the go-enum command to generate them again.
	var _ sql.Scanner = &_nil_OperationResult_value
}

func (i OperationResult) Value() (driver.Value, error) {
	return i.String(), nil
}

func (i *OperationResult) Scan(value interface{}) error {
	if value == nil {
		return nil
	}

	str, ok := value.(string)
	if !ok {
		bytes, ok := value.([]byte)
		if !ok {
			return fmt.Errorf("value is not a byte slice")
		}

		str = string(bytes[:])
	}

	val, err := ParseOperationResultString(str)
	if err != nil {
		return err
	}

	*i = val
	return nil
}

// OperationResultSliceContains reports whether sunEnums is within enums.
func OperationResultSliceContains(enums []OperationResult, sunEnums ...OperationResult) bool {
	var seenEnums = map[OperationResult]bool{}
	for _, e := range sunEnums {
		seenEnums[e] = false
	}

	for _, v := range enums {
		if _, has := seenEnums[v]; has {
			seenEnums[v] = true
		}
	}

	for _, seen := range seenEnums {
		if !seen {
			return false
		}
	}

	return true
}

// OperationResultSliceContainsAny reports whether any sunEnum is within enums.
func OperationResultSliceContainsAny(enums []OperationResult, sunEnums ...OperationResult) bool {
	var seenEnums = map[OperationResult]struct{}{}
	for _, e := range sunEnums {
		seenEnums[e] = struct{}{}
	}

	for _, v := range enums {
		if _, has := seenEnums[v]; has {
			return true
		}
	}

	return false
}
