---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1beta1
  - v1alpha1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-modelregistry-opendatahub-io-modelregistry
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: mmodelregistry.opendatahub.io
  rules:
  - apiGroups:
    - modelregistry.opendatahub.io
    apiVersions:
    - v1alpha1
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - modelregistries
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1beta1
  - v1alpha1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-modelregistry-opendatahub-io-modelregistry
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: vmodelregistry.opendatahub.io
  rules:
  - apiGroups:
    - modelregistry.opendatahub.io
    apiVersions:
    - v1alpha1
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - modelregistries
  sideEffects: None
