apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

# Istio config patch
patches:
  - path: istio_modelregistry.yaml
  - target:
      group: modelregistry.opendatahub.io
      version: v1beta1
      kind: ModelRegistry
      name: modelregistry-sample
    path: authconfig-labels.yaml
  - target:
      group: modelregistry.opendatahub.io
      version: v1beta1
      kind: ModelRegistry
      name: modelregistry-sample
    patch: |-
      - op: replace
        path: /apiVersion
        value: modelregistry.opendatahub.io/v1alpha1

# Config map and replacements to use istio.env for cluster specific config
configMapGenerator:
  - envs:
      - istio.env
    name: modelregistry-sample-environment
generatorOptions:
  disableNameSuffixHash: true
replacements:
  - path: replacements.yaml

#+kubebuilder:scaffold:manifestskustomizesamples
