apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

# Istio config patch
patches:
  - path: istio_modelregistry.yaml

# Config map and replacements to use istio.env for cluster specific config
configMapGenerator:
  - envs:
      - istio.env
    name: modelregistry-sample-environment
generatorOptions:
  disableNameSuffixHash: true
replacements:
  - path: ../components/replacements.yaml

#+kubebuilder:scaffold:manifestskustomizesamples
