# replacements from configmap using istio.env for cluster specific config
- source:
    kind: ConfigMap
    name: modelregistry-sample-environment
    fieldPath: data.AUTH_PROVIDER
  targets:
    - select:
        kind: ModelRegistry
        name: modelregistry-sample
      fieldPaths:
        - spec.istio.authProvider
- source:
    kind: ConfigMap
    name: modelregistry-sample-environment
    fieldPath: data.AUTHCONFIG_LABELS
  targets:
    - select:
        kind: ModelRegistry
        name: modelregistry-sample
      fieldPaths:
        - spec.istio.authConfigLabels
- source:
    kind: ConfigMap
    name: modelregistry-sample-environment
    fieldPath: data.DOMAIN
  targets:
    - select:
        kind: ModelRegistry
        name: modelregistry-sample
      fieldPaths:
        - spec.istio.gateway.domain
- source:
    kind: ConfigMap
    name: modelregistry-sample-environment
    fieldPath: data.ISTIO_INGRESS
  targets:
    - select:
        kind: ModelRegistry
        name: modelregistry-sample
      fieldPaths:
        - spec.istio.gateway.istioIngress
- source:
    kind: ConfigMap
    name: modelregistry-sample-environment
    fieldPath: data.REST_CREDENTIAL_NAME
  targets:
    - select:
        kind: ModelRegistry
        name: modelregistry-sample
      fieldPaths:
        - spec.istio.gateway.restTls.credentialName
- source:
    kind: ConfigMap
    name: modelregistry-sample-environment
    fieldPath: data.GRPC_CREDENTIAL_NAME
  targets:
    - select:
        kind: ModelRegistry
        name: modelregistry-sample
      fieldPaths:
        - spec.istio.gateway.grpcTls.credentialName
