apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
spec:
  template:
    spec:
      containers:
      - name: manager
        volumeMounts:
        - name: odh-trusted-ca-bundle
          mountPath: /etc/pki/tls/custom-certs
          readOnly: true
      volumes:
      - name: odh-trusted-ca-bundle
        configMap:
          name: odh-trusted-ca-bundle
          optional: true
