# This patch injects istio config properties from service-mesh-refs configmap in the controller manager
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
spec:
  template:
    spec:
      containers:
      - name: manager
        # name must match the volume name below
        env:
          - name: DEFAULT_CONTROL_PLANE
            valueFrom:
              configMapKeyRef:
                # CONTROL_PLANE_NAME has the name of the istio smcp
                key: CONTROL_PLANE_NAME
                name: service-mesh-refs
                optional: true
          - name: DEFAULT_ISTIO_INGRESS
            valueFrom:
              configMapKeyRef:
                # ISTIO_INGRESS_NAME has the name of the istio ingress gateway
                key: ISTIO_INGRESS_NAME
                name: service-mesh-refs
                # optional to allow odh operator to add if available, defaults to `ingressgateway` otherwise
                optional: true
