apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{.Name}}-users
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: registry-user-{{.Name}}
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: {{.Name}}-users
