apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    name: metadata-db
    labels:
      component: db
  spec:
    type: ClusterIP
    ports:
      - port: 3306
        protocol: TCP
        name: dbapi
    selector:
      component: db
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: metadata-mysql
  spec:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: metadata-db
    labels:
      component: db
  spec:
    selector:
      matchLabels:
        component: db
    replicas: 1
    strategy:
      type: Recreate
    template:
      metadata:
        name: db
        labels:
          component: db
        annotations:
          sidecar.istio.io/inject: "false"
      spec:
        containers:
        - env:
          - name: MYSQL_USER_NAME
            valueFrom:
              secretKeyRef:
                key: database-user
                name: model-registry-db
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                key: database-password
                name: model-registry-db
          - name: MYSQL_DATABASE
            valueFrom:
              secretKeyRef:
                key: database-name
                name: model-registry-db
          - name: MYSQL_ALLOW_EMPTY_PASSWORD
            value: "true"
          - name: MYSQL_PORT
            value: 3306
        - name: db-container
          image: mysql:8.0.3
          args:
          - --datadir
          - /var/lib/mysql/datadir
          ports:
          - name: dbapi
            containerPort: 3306
          readinessProbe:
            exec:
              command:
              - "/bin/bash"
              - "-c"
              - "mysql -D $$MYSQL_DATABASE -p$$MYSQL_ROOT_PASSWORD -e 'SELECT 1'"
            initialDelaySeconds: 5
            periodSeconds: 2
            timeoutSeconds: 1
          volumeMounts:
          - name: metadata-mysql
            mountPath: /var/lib/mysql
        volumes:
        - name: metadata-mysql
          persistentVolumeClaim:
            claimName: metadata-mysql