//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	v1beta1 "github.com/opendatahub-io/model-registry-operator/api/v1beta1"
	v1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*ConfigMapKeyValue)(nil), (*v1beta1.ConfigMapKeyValue)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ConfigMapKeyValue_To_v1beta1_ConfigMapKeyValue(a.(*ConfigMapKeyValue), b.(*v1beta1.ConfigMapKeyValue), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.ConfigMapKeyValue)(nil), (*ConfigMapKeyValue)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_ConfigMapKeyValue_To_v1alpha1_ConfigMapKeyValue(a.(*v1beta1.ConfigMapKeyValue), b.(*ConfigMapKeyValue), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*GrpcSpec)(nil), (*v1beta1.GrpcSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_GrpcSpec_To_v1beta1_GrpcSpec(a.(*GrpcSpec), b.(*v1beta1.GrpcSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.GrpcSpec)(nil), (*GrpcSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_GrpcSpec_To_v1alpha1_GrpcSpec(a.(*v1beta1.GrpcSpec), b.(*GrpcSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ModelRegistry)(nil), (*v1beta1.ModelRegistry)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ModelRegistry_To_v1beta1_ModelRegistry(a.(*ModelRegistry), b.(*v1beta1.ModelRegistry), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.ModelRegistry)(nil), (*ModelRegistry)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_ModelRegistry_To_v1alpha1_ModelRegistry(a.(*v1beta1.ModelRegistry), b.(*ModelRegistry), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ModelRegistryList)(nil), (*v1beta1.ModelRegistryList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ModelRegistryList_To_v1beta1_ModelRegistryList(a.(*ModelRegistryList), b.(*v1beta1.ModelRegistryList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.ModelRegistryList)(nil), (*ModelRegistryList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_ModelRegistryList_To_v1alpha1_ModelRegistryList(a.(*v1beta1.ModelRegistryList), b.(*ModelRegistryList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.ModelRegistrySpec)(nil), (*ModelRegistrySpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_ModelRegistrySpec_To_v1alpha1_ModelRegistrySpec(a.(*v1beta1.ModelRegistrySpec), b.(*ModelRegistrySpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ModelRegistryStatus)(nil), (*v1beta1.ModelRegistryStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ModelRegistryStatus_To_v1beta1_ModelRegistryStatus(a.(*ModelRegistryStatus), b.(*v1beta1.ModelRegistryStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.ModelRegistryStatus)(nil), (*ModelRegistryStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_ModelRegistryStatus_To_v1alpha1_ModelRegistryStatus(a.(*v1beta1.ModelRegistryStatus), b.(*ModelRegistryStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MySQLConfig)(nil), (*v1beta1.MySQLConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_MySQLConfig_To_v1beta1_MySQLConfig(a.(*MySQLConfig), b.(*v1beta1.MySQLConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.MySQLConfig)(nil), (*MySQLConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_MySQLConfig_To_v1alpha1_MySQLConfig(a.(*v1beta1.MySQLConfig), b.(*MySQLConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*OAuthProxyConfig)(nil), (*v1beta1.OAuthProxyConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_OAuthProxyConfig_To_v1beta1_OAuthProxyConfig(a.(*OAuthProxyConfig), b.(*v1beta1.OAuthProxyConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.OAuthProxyConfig)(nil), (*OAuthProxyConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_OAuthProxyConfig_To_v1alpha1_OAuthProxyConfig(a.(*v1beta1.OAuthProxyConfig), b.(*OAuthProxyConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PostgresConfig)(nil), (*v1beta1.PostgresConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_PostgresConfig_To_v1beta1_PostgresConfig(a.(*PostgresConfig), b.(*v1beta1.PostgresConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.PostgresConfig)(nil), (*PostgresConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_PostgresConfig_To_v1alpha1_PostgresConfig(a.(*v1beta1.PostgresConfig), b.(*PostgresConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RestSpec)(nil), (*v1beta1.RestSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_RestSpec_To_v1beta1_RestSpec(a.(*RestSpec), b.(*v1beta1.RestSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.RestSpec)(nil), (*RestSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_RestSpec_To_v1alpha1_RestSpec(a.(*v1beta1.RestSpec), b.(*RestSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*SecretKeyValue)(nil), (*v1beta1.SecretKeyValue)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_SecretKeyValue_To_v1beta1_SecretKeyValue(a.(*SecretKeyValue), b.(*v1beta1.SecretKeyValue), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.SecretKeyValue)(nil), (*SecretKeyValue)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_SecretKeyValue_To_v1alpha1_SecretKeyValue(a.(*v1beta1.SecretKeyValue), b.(*SecretKeyValue), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*ModelRegistrySpec)(nil), (*v1beta1.ModelRegistrySpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ModelRegistrySpec_To_v1beta1_ModelRegistrySpec(a.(*ModelRegistrySpec), b.(*v1beta1.ModelRegistrySpec), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_ConfigMapKeyValue_To_v1beta1_ConfigMapKeyValue(in *ConfigMapKeyValue, out *v1beta1.ConfigMapKeyValue, s conversion.Scope) error {
	out.Name = in.Name
	out.Key = in.Key
	return nil
}

// Convert_v1alpha1_ConfigMapKeyValue_To_v1beta1_ConfigMapKeyValue is an autogenerated conversion function.
func Convert_v1alpha1_ConfigMapKeyValue_To_v1beta1_ConfigMapKeyValue(in *ConfigMapKeyValue, out *v1beta1.ConfigMapKeyValue, s conversion.Scope) error {
	return autoConvert_v1alpha1_ConfigMapKeyValue_To_v1beta1_ConfigMapKeyValue(in, out, s)
}

func autoConvert_v1beta1_ConfigMapKeyValue_To_v1alpha1_ConfigMapKeyValue(in *v1beta1.ConfigMapKeyValue, out *ConfigMapKeyValue, s conversion.Scope) error {
	out.Name = in.Name
	out.Key = in.Key
	return nil
}

// Convert_v1beta1_ConfigMapKeyValue_To_v1alpha1_ConfigMapKeyValue is an autogenerated conversion function.
func Convert_v1beta1_ConfigMapKeyValue_To_v1alpha1_ConfigMapKeyValue(in *v1beta1.ConfigMapKeyValue, out *ConfigMapKeyValue, s conversion.Scope) error {
	return autoConvert_v1beta1_ConfigMapKeyValue_To_v1alpha1_ConfigMapKeyValue(in, out, s)
}

func autoConvert_v1alpha1_GrpcSpec_To_v1beta1_GrpcSpec(in *GrpcSpec, out *v1beta1.GrpcSpec, s conversion.Scope) error {
	out.Port = (*int32)(unsafe.Pointer(in.Port))
	out.Resources = (*v1.ResourceRequirements)(unsafe.Pointer(in.Resources))
	out.Image = in.Image
	return nil
}

// Convert_v1alpha1_GrpcSpec_To_v1beta1_GrpcSpec is an autogenerated conversion function.
func Convert_v1alpha1_GrpcSpec_To_v1beta1_GrpcSpec(in *GrpcSpec, out *v1beta1.GrpcSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_GrpcSpec_To_v1beta1_GrpcSpec(in, out, s)
}

func autoConvert_v1beta1_GrpcSpec_To_v1alpha1_GrpcSpec(in *v1beta1.GrpcSpec, out *GrpcSpec, s conversion.Scope) error {
	out.Port = (*int32)(unsafe.Pointer(in.Port))
	out.Resources = (*v1.ResourceRequirements)(unsafe.Pointer(in.Resources))
	out.Image = in.Image
	return nil
}

// Convert_v1beta1_GrpcSpec_To_v1alpha1_GrpcSpec is an autogenerated conversion function.
func Convert_v1beta1_GrpcSpec_To_v1alpha1_GrpcSpec(in *v1beta1.GrpcSpec, out *GrpcSpec, s conversion.Scope) error {
	return autoConvert_v1beta1_GrpcSpec_To_v1alpha1_GrpcSpec(in, out, s)
}

func autoConvert_v1alpha1_ModelRegistry_To_v1beta1_ModelRegistry(in *ModelRegistry, out *v1beta1.ModelRegistry, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_ModelRegistrySpec_To_v1beta1_ModelRegistrySpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_ModelRegistryStatus_To_v1beta1_ModelRegistryStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_ModelRegistry_To_v1beta1_ModelRegistry is an autogenerated conversion function.
func Convert_v1alpha1_ModelRegistry_To_v1beta1_ModelRegistry(in *ModelRegistry, out *v1beta1.ModelRegistry, s conversion.Scope) error {
	return autoConvert_v1alpha1_ModelRegistry_To_v1beta1_ModelRegistry(in, out, s)
}

func autoConvert_v1beta1_ModelRegistry_To_v1alpha1_ModelRegistry(in *v1beta1.ModelRegistry, out *ModelRegistry, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta1_ModelRegistrySpec_To_v1alpha1_ModelRegistrySpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_ModelRegistryStatus_To_v1alpha1_ModelRegistryStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_ModelRegistry_To_v1alpha1_ModelRegistry is an autogenerated conversion function.
func Convert_v1beta1_ModelRegistry_To_v1alpha1_ModelRegistry(in *v1beta1.ModelRegistry, out *ModelRegistry, s conversion.Scope) error {
	return autoConvert_v1beta1_ModelRegistry_To_v1alpha1_ModelRegistry(in, out, s)
}

func autoConvert_v1alpha1_ModelRegistryList_To_v1beta1_ModelRegistryList(in *ModelRegistryList, out *v1beta1.ModelRegistryList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]v1beta1.ModelRegistry, len(*in))
		for i := range *in {
			if err := Convert_v1alpha1_ModelRegistry_To_v1beta1_ModelRegistry(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha1_ModelRegistryList_To_v1beta1_ModelRegistryList is an autogenerated conversion function.
func Convert_v1alpha1_ModelRegistryList_To_v1beta1_ModelRegistryList(in *ModelRegistryList, out *v1beta1.ModelRegistryList, s conversion.Scope) error {
	return autoConvert_v1alpha1_ModelRegistryList_To_v1beta1_ModelRegistryList(in, out, s)
}

func autoConvert_v1beta1_ModelRegistryList_To_v1alpha1_ModelRegistryList(in *v1beta1.ModelRegistryList, out *ModelRegistryList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ModelRegistry, len(*in))
		for i := range *in {
			if err := Convert_v1beta1_ModelRegistry_To_v1alpha1_ModelRegistry(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1beta1_ModelRegistryList_To_v1alpha1_ModelRegistryList is an autogenerated conversion function.
func Convert_v1beta1_ModelRegistryList_To_v1alpha1_ModelRegistryList(in *v1beta1.ModelRegistryList, out *ModelRegistryList, s conversion.Scope) error {
	return autoConvert_v1beta1_ModelRegistryList_To_v1alpha1_ModelRegistryList(in, out, s)
}

func autoConvert_v1alpha1_ModelRegistrySpec_To_v1beta1_ModelRegistrySpec(in *ModelRegistrySpec, out *v1beta1.ModelRegistrySpec, s conversion.Scope) error {
	if err := Convert_v1alpha1_RestSpec_To_v1beta1_RestSpec(&in.Rest, &out.Rest, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_GrpcSpec_To_v1beta1_GrpcSpec(&in.Grpc, &out.Grpc, s); err != nil {
		return err
	}
	out.Postgres = (*v1beta1.PostgresConfig)(unsafe.Pointer(in.Postgres))
	out.MySQL = (*v1beta1.MySQLConfig)(unsafe.Pointer(in.MySQL))
	out.EnableDatabaseUpgrade = (*bool)(unsafe.Pointer(in.EnableDatabaseUpgrade))
	out.DowngradeDbSchemaVersion = (*int64)(unsafe.Pointer(in.DowngradeDbSchemaVersion))
	// WARNING: in.Istio requires manual conversion: does not exist in peer-type
	out.OAuthProxy = (*v1beta1.OAuthProxyConfig)(unsafe.Pointer(in.OAuthProxy))
	return nil
}

func autoConvert_v1beta1_ModelRegistrySpec_To_v1alpha1_ModelRegistrySpec(in *v1beta1.ModelRegistrySpec, out *ModelRegistrySpec, s conversion.Scope) error {
	if err := Convert_v1beta1_RestSpec_To_v1alpha1_RestSpec(&in.Rest, &out.Rest, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_GrpcSpec_To_v1alpha1_GrpcSpec(&in.Grpc, &out.Grpc, s); err != nil {
		return err
	}
	out.Postgres = (*PostgresConfig)(unsafe.Pointer(in.Postgres))
	out.MySQL = (*MySQLConfig)(unsafe.Pointer(in.MySQL))
	out.EnableDatabaseUpgrade = (*bool)(unsafe.Pointer(in.EnableDatabaseUpgrade))
	out.DowngradeDbSchemaVersion = (*int64)(unsafe.Pointer(in.DowngradeDbSchemaVersion))
	out.OAuthProxy = (*OAuthProxyConfig)(unsafe.Pointer(in.OAuthProxy))
	return nil
}

// Convert_v1beta1_ModelRegistrySpec_To_v1alpha1_ModelRegistrySpec is an autogenerated conversion function.
func Convert_v1beta1_ModelRegistrySpec_To_v1alpha1_ModelRegistrySpec(in *v1beta1.ModelRegistrySpec, out *ModelRegistrySpec, s conversion.Scope) error {
	return autoConvert_v1beta1_ModelRegistrySpec_To_v1alpha1_ModelRegistrySpec(in, out, s)
}

func autoConvert_v1alpha1_ModelRegistryStatus_To_v1beta1_ModelRegistryStatus(in *ModelRegistryStatus, out *v1beta1.ModelRegistryStatus, s conversion.Scope) error {
	out.Hosts = *(*[]string)(unsafe.Pointer(&in.Hosts))
	out.HostsStr = in.HostsStr
	out.SpecDefaults = in.SpecDefaults
	out.Conditions = *(*[]metav1.Condition)(unsafe.Pointer(&in.Conditions))
	return nil
}

// Convert_v1alpha1_ModelRegistryStatus_To_v1beta1_ModelRegistryStatus is an autogenerated conversion function.
func Convert_v1alpha1_ModelRegistryStatus_To_v1beta1_ModelRegistryStatus(in *ModelRegistryStatus, out *v1beta1.ModelRegistryStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_ModelRegistryStatus_To_v1beta1_ModelRegistryStatus(in, out, s)
}

func autoConvert_v1beta1_ModelRegistryStatus_To_v1alpha1_ModelRegistryStatus(in *v1beta1.ModelRegistryStatus, out *ModelRegistryStatus, s conversion.Scope) error {
	out.Hosts = *(*[]string)(unsafe.Pointer(&in.Hosts))
	out.HostsStr = in.HostsStr
	out.SpecDefaults = in.SpecDefaults
	out.Conditions = *(*[]metav1.Condition)(unsafe.Pointer(&in.Conditions))
	return nil
}

// Convert_v1beta1_ModelRegistryStatus_To_v1alpha1_ModelRegistryStatus is an autogenerated conversion function.
func Convert_v1beta1_ModelRegistryStatus_To_v1alpha1_ModelRegistryStatus(in *v1beta1.ModelRegistryStatus, out *ModelRegistryStatus, s conversion.Scope) error {
	return autoConvert_v1beta1_ModelRegistryStatus_To_v1alpha1_ModelRegistryStatus(in, out, s)
}

func autoConvert_v1alpha1_MySQLConfig_To_v1beta1_MySQLConfig(in *MySQLConfig, out *v1beta1.MySQLConfig, s conversion.Scope) error {
	out.Host = in.Host
	out.Port = (*int32)(unsafe.Pointer(in.Port))
	out.Username = in.Username
	out.PasswordSecret = (*v1beta1.SecretKeyValue)(unsafe.Pointer(in.PasswordSecret))
	out.Database = in.Database
	out.SkipDBCreation = in.SkipDBCreation
	out.SSLCertificateSecret = (*v1beta1.SecretKeyValue)(unsafe.Pointer(in.SSLCertificateSecret))
	out.SSLKeySecret = (*v1beta1.SecretKeyValue)(unsafe.Pointer(in.SSLKeySecret))
	out.SSLRootCertificateConfigMap = (*v1beta1.ConfigMapKeyValue)(unsafe.Pointer(in.SSLRootCertificateConfigMap))
	out.SSLRootCertificatesConfigMapName = (*string)(unsafe.Pointer(in.SSLRootCertificatesConfigMapName))
	out.SSLRootCertificateSecret = (*v1beta1.SecretKeyValue)(unsafe.Pointer(in.SSLRootCertificateSecret))
	out.SSLRootCertificatesSecretName = (*string)(unsafe.Pointer(in.SSLRootCertificatesSecretName))
	out.SSLCipher = (*string)(unsafe.Pointer(in.SSLCipher))
	out.VerifyServerCert = (*bool)(unsafe.Pointer(in.VerifyServerCert))
	return nil
}

// Convert_v1alpha1_MySQLConfig_To_v1beta1_MySQLConfig is an autogenerated conversion function.
func Convert_v1alpha1_MySQLConfig_To_v1beta1_MySQLConfig(in *MySQLConfig, out *v1beta1.MySQLConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_MySQLConfig_To_v1beta1_MySQLConfig(in, out, s)
}

func autoConvert_v1beta1_MySQLConfig_To_v1alpha1_MySQLConfig(in *v1beta1.MySQLConfig, out *MySQLConfig, s conversion.Scope) error {
	out.Host = in.Host
	out.Port = (*int32)(unsafe.Pointer(in.Port))
	out.Username = in.Username
	out.PasswordSecret = (*SecretKeyValue)(unsafe.Pointer(in.PasswordSecret))
	out.Database = in.Database
	out.SkipDBCreation = in.SkipDBCreation
	out.SSLCertificateSecret = (*SecretKeyValue)(unsafe.Pointer(in.SSLCertificateSecret))
	out.SSLKeySecret = (*SecretKeyValue)(unsafe.Pointer(in.SSLKeySecret))
	out.SSLRootCertificateConfigMap = (*ConfigMapKeyValue)(unsafe.Pointer(in.SSLRootCertificateConfigMap))
	out.SSLRootCertificatesConfigMapName = (*string)(unsafe.Pointer(in.SSLRootCertificatesConfigMapName))
	out.SSLRootCertificateSecret = (*SecretKeyValue)(unsafe.Pointer(in.SSLRootCertificateSecret))
	out.SSLRootCertificatesSecretName = (*string)(unsafe.Pointer(in.SSLRootCertificatesSecretName))
	out.SSLCipher = (*string)(unsafe.Pointer(in.SSLCipher))
	out.VerifyServerCert = (*bool)(unsafe.Pointer(in.VerifyServerCert))
	return nil
}

// Convert_v1beta1_MySQLConfig_To_v1alpha1_MySQLConfig is an autogenerated conversion function.
func Convert_v1beta1_MySQLConfig_To_v1alpha1_MySQLConfig(in *v1beta1.MySQLConfig, out *MySQLConfig, s conversion.Scope) error {
	return autoConvert_v1beta1_MySQLConfig_To_v1alpha1_MySQLConfig(in, out, s)
}

func autoConvert_v1alpha1_OAuthProxyConfig_To_v1beta1_OAuthProxyConfig(in *OAuthProxyConfig, out *v1beta1.OAuthProxyConfig, s conversion.Scope) error {
	out.Port = (*int32)(unsafe.Pointer(in.Port))
	out.TLSCertificateSecret = (*v1beta1.SecretKeyValue)(unsafe.Pointer(in.TLSCertificateSecret))
	out.TLSKeySecret = (*v1beta1.SecretKeyValue)(unsafe.Pointer(in.TLSKeySecret))
	out.ServiceRoute = in.ServiceRoute
	out.Domain = in.Domain
	out.RoutePort = (*int32)(unsafe.Pointer(in.RoutePort))
	out.Image = in.Image
	return nil
}

// Convert_v1alpha1_OAuthProxyConfig_To_v1beta1_OAuthProxyConfig is an autogenerated conversion function.
func Convert_v1alpha1_OAuthProxyConfig_To_v1beta1_OAuthProxyConfig(in *OAuthProxyConfig, out *v1beta1.OAuthProxyConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_OAuthProxyConfig_To_v1beta1_OAuthProxyConfig(in, out, s)
}

func autoConvert_v1beta1_OAuthProxyConfig_To_v1alpha1_OAuthProxyConfig(in *v1beta1.OAuthProxyConfig, out *OAuthProxyConfig, s conversion.Scope) error {
	out.Port = (*int32)(unsafe.Pointer(in.Port))
	out.TLSCertificateSecret = (*SecretKeyValue)(unsafe.Pointer(in.TLSCertificateSecret))
	out.TLSKeySecret = (*SecretKeyValue)(unsafe.Pointer(in.TLSKeySecret))
	out.ServiceRoute = in.ServiceRoute
	out.Domain = in.Domain
	out.RoutePort = (*int32)(unsafe.Pointer(in.RoutePort))
	out.Image = in.Image
	return nil
}

// Convert_v1beta1_OAuthProxyConfig_To_v1alpha1_OAuthProxyConfig is an autogenerated conversion function.
func Convert_v1beta1_OAuthProxyConfig_To_v1alpha1_OAuthProxyConfig(in *v1beta1.OAuthProxyConfig, out *OAuthProxyConfig, s conversion.Scope) error {
	return autoConvert_v1beta1_OAuthProxyConfig_To_v1alpha1_OAuthProxyConfig(in, out, s)
}

func autoConvert_v1alpha1_PostgresConfig_To_v1beta1_PostgresConfig(in *PostgresConfig, out *v1beta1.PostgresConfig, s conversion.Scope) error {
	out.Host = in.Host
	out.HostAddress = in.HostAddress
	out.Port = (*int32)(unsafe.Pointer(in.Port))
	out.Username = in.Username
	out.PasswordSecret = (*v1beta1.SecretKeyValue)(unsafe.Pointer(in.PasswordSecret))
	out.Database = in.Database
	out.SkipDBCreation = in.SkipDBCreation
	out.SSLMode = in.SSLMode
	out.SSLCertificateSecret = (*v1beta1.SecretKeyValue)(unsafe.Pointer(in.SSLCertificateSecret))
	out.SSLKeySecret = (*v1beta1.SecretKeyValue)(unsafe.Pointer(in.SSLKeySecret))
	out.SSLPasswordSecret = (*v1beta1.SecretKeyValue)(unsafe.Pointer(in.SSLPasswordSecret))
	out.SSLRootCertificateConfigMap = (*v1beta1.ConfigMapKeyValue)(unsafe.Pointer(in.SSLRootCertificateConfigMap))
	out.SSLRootCertificateSecret = (*v1beta1.SecretKeyValue)(unsafe.Pointer(in.SSLRootCertificateSecret))
	return nil
}

// Convert_v1alpha1_PostgresConfig_To_v1beta1_PostgresConfig is an autogenerated conversion function.
func Convert_v1alpha1_PostgresConfig_To_v1beta1_PostgresConfig(in *PostgresConfig, out *v1beta1.PostgresConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_PostgresConfig_To_v1beta1_PostgresConfig(in, out, s)
}

func autoConvert_v1beta1_PostgresConfig_To_v1alpha1_PostgresConfig(in *v1beta1.PostgresConfig, out *PostgresConfig, s conversion.Scope) error {
	out.Host = in.Host
	out.HostAddress = in.HostAddress
	out.Port = (*int32)(unsafe.Pointer(in.Port))
	out.Username = in.Username
	out.PasswordSecret = (*SecretKeyValue)(unsafe.Pointer(in.PasswordSecret))
	out.Database = in.Database
	out.SkipDBCreation = in.SkipDBCreation
	out.SSLMode = in.SSLMode
	out.SSLCertificateSecret = (*SecretKeyValue)(unsafe.Pointer(in.SSLCertificateSecret))
	out.SSLKeySecret = (*SecretKeyValue)(unsafe.Pointer(in.SSLKeySecret))
	out.SSLPasswordSecret = (*SecretKeyValue)(unsafe.Pointer(in.SSLPasswordSecret))
	out.SSLRootCertificateConfigMap = (*ConfigMapKeyValue)(unsafe.Pointer(in.SSLRootCertificateConfigMap))
	out.SSLRootCertificateSecret = (*SecretKeyValue)(unsafe.Pointer(in.SSLRootCertificateSecret))
	return nil
}

// Convert_v1beta1_PostgresConfig_To_v1alpha1_PostgresConfig is an autogenerated conversion function.
func Convert_v1beta1_PostgresConfig_To_v1alpha1_PostgresConfig(in *v1beta1.PostgresConfig, out *PostgresConfig, s conversion.Scope) error {
	return autoConvert_v1beta1_PostgresConfig_To_v1alpha1_PostgresConfig(in, out, s)
}

func autoConvert_v1alpha1_RestSpec_To_v1beta1_RestSpec(in *RestSpec, out *v1beta1.RestSpec, s conversion.Scope) error {
	out.Port = (*int32)(unsafe.Pointer(in.Port))
	out.ServiceRoute = in.ServiceRoute
	out.Resources = (*v1.ResourceRequirements)(unsafe.Pointer(in.Resources))
	out.Image = in.Image
	return nil
}

// Convert_v1alpha1_RestSpec_To_v1beta1_RestSpec is an autogenerated conversion function.
func Convert_v1alpha1_RestSpec_To_v1beta1_RestSpec(in *RestSpec, out *v1beta1.RestSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_RestSpec_To_v1beta1_RestSpec(in, out, s)
}

func autoConvert_v1beta1_RestSpec_To_v1alpha1_RestSpec(in *v1beta1.RestSpec, out *RestSpec, s conversion.Scope) error {
	out.Port = (*int32)(unsafe.Pointer(in.Port))
	out.ServiceRoute = in.ServiceRoute
	out.Resources = (*v1.ResourceRequirements)(unsafe.Pointer(in.Resources))
	out.Image = in.Image
	return nil
}

// Convert_v1beta1_RestSpec_To_v1alpha1_RestSpec is an autogenerated conversion function.
func Convert_v1beta1_RestSpec_To_v1alpha1_RestSpec(in *v1beta1.RestSpec, out *RestSpec, s conversion.Scope) error {
	return autoConvert_v1beta1_RestSpec_To_v1alpha1_RestSpec(in, out, s)
}

func autoConvert_v1alpha1_SecretKeyValue_To_v1beta1_SecretKeyValue(in *SecretKeyValue, out *v1beta1.SecretKeyValue, s conversion.Scope) error {
	out.Name = in.Name
	out.Key = in.Key
	return nil
}

// Convert_v1alpha1_SecretKeyValue_To_v1beta1_SecretKeyValue is an autogenerated conversion function.
func Convert_v1alpha1_SecretKeyValue_To_v1beta1_SecretKeyValue(in *SecretKeyValue, out *v1beta1.SecretKeyValue, s conversion.Scope) error {
	return autoConvert_v1alpha1_SecretKeyValue_To_v1beta1_SecretKeyValue(in, out, s)
}

func autoConvert_v1beta1_SecretKeyValue_To_v1alpha1_SecretKeyValue(in *v1beta1.SecretKeyValue, out *SecretKeyValue, s conversion.Scope) error {
	out.Name = in.Name
	out.Key = in.Key
	return nil
}

// Convert_v1beta1_SecretKeyValue_To_v1alpha1_SecretKeyValue is an autogenerated conversion function.
func Convert_v1beta1_SecretKeyValue_To_v1alpha1_SecretKeyValue(in *v1beta1.SecretKeyValue, out *SecretKeyValue, s conversion.Scope) error {
	return autoConvert_v1beta1_SecretKeyValue_To_v1alpha1_SecretKeyValue(in, out, s)
}
