//go:build !ignore_autogenerated

/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Catalog) DeepCopyInto(out *Catalog) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Catalog.
func (in *Catalog) DeepCopy() *Catalog {
	if in == nil {
		return nil
	}
	out := new(Catalog)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Catalog) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CatalogDatabase) DeepCopyInto(out *CatalogDatabase) {
	*out = *in
	in.Volume.DeepCopyInto(&out.Volume)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CatalogDatabase.
func (in *CatalogDatabase) DeepCopy() *CatalogDatabase {
	if in == nil {
		return nil
	}
	out := new(CatalogDatabase)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CatalogDatabaseVolume) DeepCopyInto(out *CatalogDatabaseVolume) {
	*out = *in
	if in.SizeLimit != nil {
		in, out := &in.SizeLimit, &out.SizeLimit
		x := (*in).DeepCopy()
		*out = &x
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CatalogDatabaseVolume.
func (in *CatalogDatabaseVolume) DeepCopy() *CatalogDatabaseVolume {
	if in == nil {
		return nil
	}
	out := new(CatalogDatabaseVolume)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CatalogImageAttempt) DeepCopyInto(out *CatalogImageAttempt) {
	*out = *in
	out.RequestedSelection = in.RequestedSelection
	if in.ResolvedImages != nil {
		in, out := &in.ResolvedImages, &out.ResolvedImages
		*out = new(CatalogResolvedImages)
		**out = **in
	}
	in.SelectionOutcome.DeepCopyInto(&out.SelectionOutcome)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CatalogImageAttempt.
func (in *CatalogImageAttempt) DeepCopy() *CatalogImageAttempt {
	if in == nil {
		return nil
	}
	out := new(CatalogImageAttempt)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CatalogImageOutcome) DeepCopyInto(out *CatalogImageOutcome) {
	*out = *in
	if in.Images != nil {
		in, out := &in.Images, &out.Images
		*out = new(CatalogImageReferences)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CatalogImageOutcome.
func (in *CatalogImageOutcome) DeepCopy() *CatalogImageOutcome {
	if in == nil {
		return nil
	}
	out := new(CatalogImageOutcome)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CatalogImageReferences) DeepCopyInto(out *CatalogImageReferences) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CatalogImageReferences.
func (in *CatalogImageReferences) DeepCopy() *CatalogImageReferences {
	if in == nil {
		return nil
	}
	out := new(CatalogImageReferences)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CatalogImageSelections) DeepCopyInto(out *CatalogImageSelections) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CatalogImageSelections.
func (in *CatalogImageSelections) DeepCopy() *CatalogImageSelections {
	if in == nil {
		return nil
	}
	out := new(CatalogImageSelections)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CatalogImageSource) DeepCopyInto(out *CatalogImageSource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CatalogImageSource.
func (in *CatalogImageSource) DeepCopy() *CatalogImageSource {
	if in == nil {
		return nil
	}
	out := new(CatalogImageSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CatalogImageUpdateStatus) DeepCopyInto(out *CatalogImageUpdateStatus) {
	*out = *in
	in.CurrentAttempt.DeepCopyInto(&out.CurrentAttempt)
	if in.ActivationOutcome != nil {
		in, out := &in.ActivationOutcome, &out.ActivationOutcome
		*out = new(CatalogImageOutcome)
		(*in).DeepCopyInto(*out)
	}
	if in.LastFailure != nil {
		in, out := &in.LastFailure, &out.LastFailure
		*out = new(CatalogImageOutcome)
		(*in).DeepCopyInto(*out)
	}
	if in.LastSuccessfulActivation != nil {
		in, out := &in.LastSuccessfulActivation, &out.LastSuccessfulActivation
		*out = new(CatalogSuccessfulActivation)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CatalogImageUpdateStatus.
func (in *CatalogImageUpdateStatus) DeepCopy() *CatalogImageUpdateStatus {
	if in == nil {
		return nil
	}
	out := new(CatalogImageUpdateStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CatalogList) DeepCopyInto(out *CatalogList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Catalog, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CatalogList.
func (in *CatalogList) DeepCopy() *CatalogList {
	if in == nil {
		return nil
	}
	out := new(CatalogList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CatalogList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CatalogResolvedImage) DeepCopyInto(out *CatalogResolvedImage) {
	*out = *in
	out.Source = in.Source
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CatalogResolvedImage.
func (in *CatalogResolvedImage) DeepCopy() *CatalogResolvedImage {
	if in == nil {
		return nil
	}
	out := new(CatalogResolvedImage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CatalogResolvedImages) DeepCopyInto(out *CatalogResolvedImages) {
	*out = *in
	out.Catalog = in.Catalog
	out.Benchmark = in.Benchmark
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CatalogResolvedImages.
func (in *CatalogResolvedImages) DeepCopy() *CatalogResolvedImages {
	if in == nil {
		return nil
	}
	out := new(CatalogResolvedImages)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CatalogResources) DeepCopyInto(out *CatalogResources) {
	*out = *in
	if in.Catalog != nil {
		in, out := &in.Catalog, &out.Catalog
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.Postgres != nil {
		in, out := &in.Postgres, &out.Postgres
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CatalogResources.
func (in *CatalogResources) DeepCopy() *CatalogResources {
	if in == nil {
		return nil
	}
	out := new(CatalogResources)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CatalogSpec) DeepCopyInto(out *CatalogSpec) {
	*out = *in
	in.Resources.DeepCopyInto(&out.Resources)
	in.Database.DeepCopyInto(&out.Database)
	if in.CatalogDataImageStream != nil {
		in, out := &in.CatalogDataImageStream, &out.CatalogDataImageStream
		*out = new(string)
		**out = **in
	}
	if in.BenchmarkDataImageStream != nil {
		in, out := &in.BenchmarkDataImageStream, &out.BenchmarkDataImageStream
		*out = new(string)
		**out = **in
	}
	if in.Proxy != nil {
		in, out := &in.Proxy, &out.Proxy
		*out = new(ProxyConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CatalogSpec.
func (in *CatalogSpec) DeepCopy() *CatalogSpec {
	if in == nil {
		return nil
	}
	out := new(CatalogSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CatalogStatus) DeepCopyInto(out *CatalogStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ImageUpdate != nil {
		in, out := &in.ImageUpdate, &out.ImageUpdate
		*out = new(CatalogImageUpdateStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CatalogStatus.
func (in *CatalogStatus) DeepCopy() *CatalogStatus {
	if in == nil {
		return nil
	}
	out := new(CatalogStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CatalogSuccessfulActivation) DeepCopyInto(out *CatalogSuccessfulActivation) {
	*out = *in
	out.Images = in.Images
	in.ActivatedAt.DeepCopyInto(&out.ActivatedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CatalogSuccessfulActivation.
func (in *CatalogSuccessfulActivation) DeepCopy() *CatalogSuccessfulActivation {
	if in == nil {
		return nil
	}
	out := new(CatalogSuccessfulActivation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProxyConfig) DeepCopyInto(out *ProxyConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProxyConfig.
func (in *ProxyConfig) DeepCopy() *ProxyConfig {
	if in == nil {
		return nil
	}
	out := new(ProxyConfig)
	in.DeepCopyInto(out)
	return out
}
