apiVersion: modelregistry.opendatahub.io/v1alpha1
kind: ModelRegistry
metadata:
  name: modelregistry-sample
spec:
  mysql:
    sslRootCertificateConfigMap:
      name: model-registry-db-credential
      key: ca.crt
