---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base

# Config map and replacements to use params.env for rhoai opendatahub-operator
configMapGenerator:
- envs:
    - params.env
  name: model-registry-operator-parameters
  behavior: merge



