name: Main controller image build and tag

on:
  push:
    branches:
      - 'main'

env:
  QUAY_ORG: opendatahub
  QUAY_IMG_REPO: model-registry-operator
  QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
  QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}
  PUSH_IMAGE: true

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Generate Tag
        shell: bash
        id: tags
        run: |
          commit_sha=${{ github.event.after }}
          tag=main-${commit_sha:0:7}
          echo "tag=${tag}" >> $GITHUB_OUTPUT
      - name: Build and Push Image
        shell: bash
        env:
          VERSION: ${{ steps.tags.outputs.tag }}
        run: ./scripts/build_deploy.sh
      - name: Tag Latest
        shell: bash
        env:
          IMG: quay.io/${{ env.QUAY_ORG }}/${{ env.QUAY_IMG_REPO }}
          BUILD_IMAGE: false
          NEWEST_TAG: ${{ steps.tags.outputs.tag }}
          VERSION: latest
        run: |
          docker tag ${{ env.IMG }}:${{ env.NEWEST_TAG }} ${{ env.IMG }}:${{ env.VERSION }}
          # BUILD_IMAGE=false skip the build
          ./scripts/build_deploy.sh
      - name: Tag Main
        shell: bash
        env:
          IMG: quay.io/${{ env.QUAY_ORG }}/${{ env.QUAY_IMG_REPO }}
          BUILD_IMAGE: false
          NEWEST_TAG: ${{ steps.tags.outputs.tag }}
          VERSION: main
        run: |
          docker tag ${{ env.IMG }}:${{ env.NEWEST_TAG }} ${{ env.IMG }}:${{ env.VERSION }}
          # BUILD_IMAGE=false skip the build
          ./scripts/build_deploy.sh
